### ISSUE TITLE
Data Analysis - when I change Units per Rotation to 0.2199115 gets an error

### ISSUE THREAD

**Issue by tkchan007** [bb-frc-workshops/romi-examples#13]
When I tried to change the Units to Meters and then enter in 0.2199115 as the Units per Rotation, I get the following error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\python\python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "c:\python\python39\lib\site-packages\frc_characterization\logger_analyzer\data_analyzer.py", line 213, in runAnalysis
    test_runners[Tests(self.test.get())]()
  File "c:\python\python39\lib\site-packages\frc_characterization\logger_analyzer\data_analyzer.py", line 234, in runAnalysisDrive
    self.track_width.set(calcTrackWidth(self.stored_data["track-width"]))
  File "c:\python\python39\lib\site-packages\frc_characterization\logger_analyzer\data_analyzer.py", line 359, in calcTrackWidth
    (self.stored_data["unitsPerRotation"] * initial_units)
TypeError: unsupported operand type(s) for *: 'float' and 'Units'

**Comment by zhiquanyeo** [comment]
This should actually get filed here: https://github.com/wpilibsuite/frc-characterization/issues  It looks like it's an issue with the characterization tool itself
